package org.torrentloom.loom.weft.release

import kotlinx.serialization.Serializable

/**
 * Well known streaming and VOD services.
 */
@Serializable
enum class Service(vararg val alternativeNames: String) {
    ADN("Animation Digital Network"),
    AE("A&E"),
    AJAZ("Al Jazeera English"),
    ALL4("Channel 4", "4OD", "All4 (Channel 4, ex-4oD)"),
    AMBC("ABC (US)", "ABC"),
    AMC,
    AMZN("Amazon Prime", "AMZN-CBR", "Amazon", "Amazon-Prime", "AmazonPrime", "Amazon, Prime Video"),
    ANLB("AnimeLab"),
    ANPL("Animal Planet"),
    AOL,
    ARD,
    AS("Adult Swim", "Adult-Swim", "AdultSwim"),
    ATK("America's Test Kitchen"),
    ATVP("AppleTV", "Apple TV+", "ATV+"),
    AUBC("ABC Australia", "ABC (AU) iView"),
    BCORE,
    BKPL("Blackpills"),
    BLU("BluTV"),
    BNGE("Binge"),
    BOOM("Boomerang"),
    BRAV("BravoTV"),
    CBC,
    CBS,
    CC("Comedy Central", "Comedy-Central", "ComedyCentral"),
    CCGC("Comedians in Cars Getting Coffee"),
    CHGD("CHRGD"),
    CLBI("Club illico"),
    CMAX("Cinemax"),
    CMOR("C More"),
    CMT("Country Music Television"),
    CN("Cartoon Network"),
    CNBC,
    CNLP("Canal+"),
    COOK("Cooking Channel"),
    CORE,
    CR("Crunchy Roll", "Crunchy-Roll", "CrunchyRoll"),
    CRAV("Crave"),
    CRIT("Criterion", "Criterion Channel"),
    CRKL("Crackle"),
    CSPN("CSpan"),
    CTV,
    CUR("CuriosityStream"),
    CW("The CW", "The-CW", "TheCW"),
    CWS("CWSeed"),
    DAZN,
    DCU("DC Universe"),
    DDY("Digiturk Diledigin Yerde", "Digiturk Dilediğin Yerde"),
    DEST("Destination America"),
    DF("DramaFever"),
    DHF("Deadhouse Films"),
    DISC("Discovery", "Discovery Channel"),
    DIY("DIY Network"),
    DOCC("Doc Club"),
    DPLY("DPlay", "DPlay (Rebranded as Discovery+)"),
    DRPO("Dropout"),
    DRTV,
    DSCP("Discovery Plus", "Discovery+"),
    DSKI("Daisuki"),
    DSNP("Disney+"),
    DSNY("Disney"),
    DTV("DirecTV Now"),
    EPIX,
    ESPN,
    ESQ("Esquire"),
    ETTV("El Trece"),
    ETV("E!"),
    FAM("Family"),
    FANDOR,
    FBWatch("Facebook Watch"),
    FJR("Family Jr"),
    FOOD("Food Network"),
    FOX,
    FOXP("Fox Premium"),
    FP("UFC Fight Pass"),
    FPT("FPT Play"),
    FREE("Freeform"),
    FTV("France.tv"),
    FUNI("Funimation"),
    FXTL("Foxtel", "Foxtel Now"),
    FYI("FYI Network"),
    GC("NHL GameCenter"),
    GLBL("Global"),
    GLOB("GloboSat Play"),
    GO90,
    Gaga("GagaOOLala"),
    HBO("HBO Go", "HBO-Go", "HBOGo"),
    HGTV,
    HIDI("HIDIVE"),
    HIST("History", "History Channel"),
    HLMK("Hallmark"),
    HMAX("HBO Max"),
    HTSR("HS", "Hotstar"),
    HULU,
    HoiChoi("HoiChoi Originals"),
    ID("Investigation Discovery"),
    IFC,
    IFX("iflix"),
    INA("National Audiovisual Institute"),
    ITV,
    KAYO("Kayo Sports"),
    KNOW("Knowledge Network"),
    KNPY("Kanopy"),
    LIFE("Lifetime"),
    LN("Loving Nature"),
    MA("Movies Anywhere"),
    MAX,
    MBC("MBCVOD"),
    MNBC("MSNBC"),
    MTOD("Motor Trend OnDemand"),
    MTV,
    MUBI,
    NATG("National Geographic", "National-Geographic", "NationalGeographic"),
    NBA("NBA TV", "NBA-TV", "NBATV", "NBA League Pass"),
    NBC,
    NF("Netflix"),
    NFB("National Film Board"),
    NFL("NFL Network"),
    NFLN("NFL Now"),
    NICK("Nickelodeon", "NICKAPP"),
    NOW("Now (Sky)"),
    NRK("Norsk Rikskringkasting"),
    ODK("OnDemandKorea"),
    OPTO,
    OWN("Oprah Winfrey Network"),
    OXGN("Oxygen"),
    PA("Project Alpha"),
    PBS,
    PBSK("PBS Kids"),
    PCOK("Peacock"),
    PLAY("Google Play"),
    PLUZ("Pluzz"),
    PMNT("Paramount Network"),
    PMTP("Paramount+", "PMNP", "PMT+", "ParamountPlus"),
    POGO("PokerGO"),
    PSN("Playstation Network"),
    PUHU("puhutv"),
    QIBI("Quibi"),
    RED("YouTube Red"),
    RKTN("Rakuten TV"),
    ROKU("The Roku Channel"),
    RSTR("Rooster Teeth"),
    RTE("RTÉ", "RTE One"),
    RUUTU,
    SBS("SBS (AU)"),
    SCI("Science Channel"),
    SESO("SeeSo"),
    SHDR("Shudder"),
    SHMI("Shomi"),
    SHO("Showtime"),
    SKST("SkyShowtime"),
    SNET("Sportsnet"),
    SONY,
    SPIK("Spike"),
    SPKE("Spike TV", "Spike-TV", "SpikeTV"),
    SPRT("Sprout"),
    STAN,
    STRP("Star+"),
    STZ("Starz"),
    SVT("Sveriges Television"),
    SWER("SwearNet"),
    SYFY,
    TBS,
    TEN("TenPlay"),
    TFOU,
    TIMV("TIMvision"),
    TLC,
    TOU("Ici TOU.TV"),
    TRVL("Travel Channel"),
    TUBI("TubiTV"),
    TV3("TV3 (IE)", "TV3 Ireland"),
    TV4("TV4 (SE)", "TV4 Sweeden"),
    TVING,
    TVL("TV Land", "TV-Land", "TVLand"),
    TVNZ,
    UFC,
    UKTV,
    UNIV("Univision"),
    USAN("USA Network"),
    VH1,
    VIAP("Viaplay"),
    VICE("Viceland"),
    VIKI,
    VLCT("Velocity"),
    VMEO("Vimeo"),
    VRV,
    VTRN("VET Tv"),
    VUDU,
    WME("WatchMe"),
    WNET("W Network"),
    WWEN("WWE Network"),
    XBOX("Xbox Video"),
    YHOO("Yahoo"),
    YT("YouTube Movies"),
    ZDF,
    `9NOW`,
    iP("BBC iPlayer", "BBC-iPlayer", "BBCiPlayer"),
    iQIYI("Qiyi"),
    iT("iTunes");

    companion object {
        fun find(searchString: String): Service? = Service.entries.find { service ->
            searchString.lowercase() in (listOf(service.name) + service.alternativeNames).map { it.lowercase() }
        }
    }
}
